
version: '3.1'

services:
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: 192.168.1.200

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_ARBITRARY=1